/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#f3f4f6",
        "outline": "#717978",
        "secondary": "#7d5800",
        "tertiary-container": "#362b16",
        "on-surface-variant": "#404848",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#755100",
        "primary-container": "#f0fdf4",
        "on-error-container": "#93000a",
        "surface": "#ffffff",
        "background": "#ffffff",
        "secondary-fixed-dim": "#f6bd54",
        "surface-container-low": "#f9fafb",
        "secondary-container": "#ffc55b",
        "on-background": "#000000",
        "on-primary-fixed-variant": "#234d4e",
        "inverse-primary": "#a3cfcf",
        "inverse-on-surface": "#f0f1f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2e4",
        "surface-container-high": "#f3f4f6",
        "surface-dim": "#d9dadc",
        "tertiary": "#201705",
        "surface-bright": "#ffffff",
        "on-tertiary-fixed": "#241a07",
        "primary": "#013334",
        "outline-variant": "#c0c8c8",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#52452e",
        "on-primary": "#ffffff",
        "surface-tint": "#013334",
        "on-primary-container": "#013334",
        "on-tertiary-container": "#a39276",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdea9",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#f4e0c1",
        "primary-fixed": "#bfebeb",
        "on-secondary-fixed": "#271900",
        "on-error": "#ffffff",
        "surface-container": "#f9fafb",
        "on-primary-fixed": "#002020",
        "on-surface": "#000000",
        "on-secondary-fixed-variant": "#5f4100",
        "primary-fixed-dim": "#a3cfcf",
        "inverse-surface": "#191c1e",
        "tertiary-fixed-dim": "#d7c4a6"
      },
      fontFamily: {
        "notoSerif": ["Noto Serif", "serif"],
        "manrope": ["Manrope", "sans-serif"],
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
